### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by subu1979** [EsharEditor/ambari-hue-service#13]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/hue_server.py", line 18, in install
    download_hue()
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/HUE/package/scripts/common.py", line 57, in download_hue
    Execute('{0} | xargs wget -O hue.tgz'.format(params.download_url))
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 273, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'cat /etc/yum.repos.d/HDP.repo | grep "baseurl" | awk -F '=' '{print $2"hue/hue-3.11.0.tgz"}' | xargs wget -O hue.tgz' returned 123. --2017-02-01 12:46:09--  http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.4.3.0hue/hue-3.11.0.tgz
Resolving public-repo-1.hortonworks.com... 54.230.191.111, 54.230.191.36, 54.230.191.119, ...
Connecting to public-repo-1.hortonworks.com|54.230.191.111|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-01 12:46:10 ERROR 404: Not Found.

**Comment by EsharEditor** [comment]
Hi subu1979:
    Sorry to reply late!
    The question：
![image](https://cloud.githubusercontent.com/assets/20943153/22581862/ff3dce18-ea1d-11e6-9b00-b0ed104ccf27.png)
   There is no HUE installation package in this repository. I think you should compile the HUE-3.11.0 and use a repository with the HUE installation package. If not,you may need to modify the code with the error section.

**Comment by subu1979** [comment]
Thanks for your reply...

**Comment by eljefewatson** [comment]
I just ran into the same issue, but in my case there is a hue release sitting in my local repository at http://edge/HDP/centos6/update/2.x/updates/2.5.3.  I locally patched the awk -F command shown above in params.py:

download_url = 'cat /etc/yum.repos.d/HDP.repo | grep "baseurl" | awk -F \'=\' \'{print $2"/hue/hue-3.12.0.tgz"}\''

It needs a missing slash in the awk command (i.e., /hue) so the URL changes from http://<repo>/HDP/centsos6/2.x/updates/2.4.3.0hue/... to http://<repo>/HDP/centos6/2.x/updates/2.4.3.0/hue/...  

I tried to add a slash to the HDP.repo which is what is being catted and grepped, but apparently during the install, that file is being rewritten by yum (repsumably) and removes the trailing slash before it gets to this awk command.

**Comment by EsharEditor** [comment]
Hi eljefewatson:
You should try to modify the URL in Ambari repository base URL,and add a slash to URL. For example:
![image](https://cloud.githubusercontent.com/assets/20943153/22816698/7cb0e9cc-ef9e-11e6-9835-abbdba522675.png)
Perhaps you can modify the command in params.py.

**Comment by Ultimacho** [comment]
I experience the same problem as in the original post (although the url is different - http://s3.amazonaws.com/dev.hortonworks.com/HDP/centos6/2.x/BUILDS/2.5.0.0-1245/hue/hue-3.11.0.tgz). So, my questions are:
1. Why does this problem occur using the original instruction and default settings?
2. What are the exact actions one should accomplish to successfully pass through the installation?

Thanks in advance!

**Comment by EsharEditor** [comment]
Hi Ultimacho:
1.There is no the Hue install-package in the original repository.
2.If you want to install the Hue successful,first of all,you need to compile the your Hue install-package. Then, It is necessary to modify the original URL with the Hue install-package or modify the code with download_url in the params.py file.

**Comment by MichalMichalak** [comment]
Could you please explain more? HDP repository for Centos has RPM packages, not TGZ. I can see in `params.py` you are creating a `download_url` by using HDP repo path and adding `hue/hue-3.11.0.tgz`. I tried to search through HDP repos and never found any TGZ file. How this `download_url` suppose to work in the first place?

If this TGZ doesn't exist, how should I create it by myself (as you suggested in last comment)? Sure I can compile official release, but what should I put in the installation TGZ anyway?

I assume it worked in the past. Maybe something has changed recently? Any help appreciated. Thanks!

**Comment by EsharEditor** [comment]
Hi MichalMichalak:
If you want to use  HDP repository, there is no RPM packages for Hue.But I was downloading the HDP repository and adding hue-3.11.0.tgz to the HDP path.

I suggest you compile the TGZ and add the TGZ to a path.Then you can modify the download_url by using this path.

**Comment by MichalMichalak** [comment]
So in other words: I must download original Hue release TGZ, unpack, compile it by myself, pack compilation result back to TGZ and then point a download URL to it. Correct?

**Comment by wuya2357** [comment]
@MichalMichalak yes,i meet the same situation.
compile hue yourself pack result back.

**Comment by MichalMichalak** [comment]
@wuya2357 Thanks for confirmation. I am afraid it isn't worth the effort, though. Ambari views gave me all what I needed, and they are there by default. I pass in this case. :)

**Comment by fairyqiqi** [comment]
I got the same problem, and I fixed it by the followings. 

1. From this link [Hue Issue 425](https://github.com/cloudera/hue/issues/425) I found that they've put hue 3.11.0 here: http://gethue.com/downloads/hue-3.11.0.tgz

2. So I modified /var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/**params.py** like this:
`download_url = 'echo http://gethue.com/downloads/hue-3.11.0.tgz'`
`hue_version_dir = 'hue-3.11.0'`

3. Then added one line in download_hue() method in /var/lib/ambari-agent/cache/stacks/HDP/2.6/services/HUE/package/scripts/**common.py** to rename the folder from hue-3.11.0 to hue.
`#Ensure all Hue files owned by hue`
**`Execute('mv {0}/{1} {2}'.format(params.hue_install_dir, params.hue_version_dir, params.hue_dir))`**
`Execute('chown -R {0}:{1} {2}'.format(params.hue_user,params.hue_group,params.hue_dir))`

4. Re-install Hue Server from Ambari and it worked.
