### ISSUE TITLE
Ambari 2.1 theme conditions not working

### ISSUE THREAD

**Issue by theyaa** [EsharEditor/ambari-hue-service#14]
Hi,
  I am trying your service and the conditions inside the theme are not working when installing in Ambari 2.1. For example

        {
          "config": "hue-desktop-site/db_user",
          "subsection-name": "subsection-hue-ms-row1-col1",
          "depends-on": [
            {
              "configs":[
                "hue-desktop-site/DB_FLAVOR"
              ],
              "if": "${hue-desktop-site/DB_FLAVOR} === sqlite3",
              "then": {
                "property_value_attributes": {
                  "visible": false
                }
              },
              "else": {
                "property_value_attributes": {
                  "visible": true
                }
              }
            }
          ]
        },

Is not working and it does not deactivate the property.

**Comment by EsharEditor** [comment]
Hi theyaa:
The ambari-hue-service of v2.0.0 is working in Ambari 2.4.0+. If you want to use it in Ambari 2.1,maybe you need to modify the code.
![image](https://cloud.githubusercontent.com/assets/20943153/22868359/f0455b92-f1cf-11e6-901e-b62f68542393.png)
