### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by LesTR** [EsharEditor/ambari-hue-service#4]
Hi,

thanks for this plugin! We wanna have hue as service in cluster and this plugin looks nice, can you please provide more details about licence for this plugin?

Thanks!

**Comment by EsharEditor** [comment]
Hi LesTR,

These is no licence,you can use it in your cluster.

**Comment by LesTR** [comment]
Hi EsharEditor,

yes, i see, there is no licence and that's the problem and we can't use it without licence.

Can you please pick one licence (Apache for example) and put information into Readme? I'll make PR if you need but i don't know what type of licence you wanna use.

Thanks!

**Comment by EsharEditor** [comment]
Hi,
I have added the Apache License,you can use it.

**Comment by LesTR** [comment]
Thanks!
