### ISSUE TITLE
Hbase Thriftserver和Zookeeper Rest服务问题

### ISSUE THREAD

**Issue by MoMaekMo** [EsharEditor/ambari-hue-service#8]
EsharEditor：
    你好！我有两个问题需要你帮忙解答。问题1：Ambari这个版本并没有提供Hbase Thriftserver,导致Hue是无法使用Hbase服务，你是通过手动启动Hbase Thriftserver服务吗？问题2：Hue服务通过Ambari安装好后，在Zookeeper模块无法操作znode，请问你是怎么解决的？
    谢谢！

**Comment by EsharEditor** [comment]
Hi MoMaekMo:

  Ambari在目前版本并没有支持Hbase thriftserver和zookeeper rest服务,安装好Hue后，需要通过手动来启动这些服务。为了方便操作，我把这几个服务的启动命令集成到了Ambari中各个组件的"Service Action"。对于zookeeper znode操作,由于我使用的HDP源并没有提供rest这块服务的源文件，解决办法是在zookeeper源安装包中找到src目录，拷贝到集群中各zookeeper节点的/usr/hdp/$VERSION/zookeeper目录下，直接命令启动：#/usr/hdp/$VERSION/zookeeper/src/contrib/rest/rest.sh start。

**Comment by MoMaekMo** [comment]
EsharEditor：
在"Service Action"添加命令的方式，会存在一些问题，如服务启动或者运行状态，如果启动的服务挂掉后，在Ambari上无法察觉的。

**Comment by EsharEditor** [comment]
嗯，是的，的确存在这样的问题。
