### ISSUE TITLE
There is no prompt to restart the hue configuration

### ISSUE THREAD

**Issue by chengwei-li** [EsharEditor/ambari-hue-service#9]
Hello, I encountered the following problems in the test hue: When I modify the configuration interface below a tab, such as Hue service Moudle, I will Hue HDFS Moudle from YES to NO, after the save did not prompt me to hue Reboot. And I still have access to HDFS Brower in the Hue WEB UI.

The same Hue User Info and Hue Databases changes also have this problem.

But when I modify the Advanced configuration properties below, will be prompted to restart. When I restart after the entry into force.

I refer to the other components of the cluster to check the next, and no similar problems. Modify the configuration will have a restart prompt.
Do not know if you have this problem? Please also help to test and provide solutions. thank you very much!

**Comment by EsharEditor** [comment]
Hi chengwei-li:

Sorry to reply late！When I modifiy the Hue HDFS Module from YES to No and restart Hue Service.I will don't have access to HDFS Brower in the Hue Web UI.It is recommended that you review the configurations of hue("app_blacklist" in "/usr/hdp/current/hue-server/desktop/conf/pseudo-distributed.ini").

It seems right in my cluster. Here is a screenshot.
![image](https://cloud.githubusercontent.com/assets/20943153/21000276/db5e5a76-bd54-11e6-9632-898d38d0c14c.png)
![image](https://cloud.githubusercontent.com/assets/20943153/21000385/7f182854-bd55-11e6-879f-e0530d15ff9e.png)

**Comment by chengwei-li** [comment]
Thanks very much for your reply! In accordance with your graphic mode of operation, there is no problem.But Perhaps my question is the following.

For example:  configs->Advanced->advance hue-hive-site
1.Modify the List Partitions Limit to 10001,as shown below
![default](https://cloud.githubusercontent.com/assets/24427835/21004456/602aba04-bd6b-11e6-8a1a-b05417ab0a65.png)
2.Execute save 
![default](https://cloud.githubusercontent.com/assets/24427835/21004430/44345be8-bd6b-11e6-9a53-76afa0311a56.png)
3.After saving, in the configuration bar on the right will be prompted to "restart".as shown below
![default](https://cloud.githubusercontent.com/assets/24427835/21004737/e2a531c0-bd6c-11e6-8808-36e6d173db6d.png)

So.When I modifiy the Hue HDFS Module from YES to No,There is no restart prompt for step 3.
We need to manually restart to take effect, As with your operating tips.
Also my question is like that. Or the Hue-service-Module part of the configuration is not associated, resulting in no restart prompt.  
I mainly want to know this piece of information. Thanks very much!

**Comment by EsharEditor** [comment]
Oh,I see what you mean.There is no restart prompt when you modifiy the Hue Module,you need to manually restart to take effect. And I have not found a good way to solve this problem.If you have any good solutions, we can communicate with each other.Maybe I need to learn more knowledge of Ambari.
Thank you for your question！

**Comment by chengwei-li** [comment]
Ok，I understand, follow-up hope that we have more communication。
Thanks for your reply again!
